/* Generated by Yosys 0.12+45 (git sha1 UNKNOWN, gcc 8.3.1 -fPIC -Os) */

module user_project_wrapper(vdda1, vdda2, vssa1, vssa2, vccd1, vccd2, vssd1, vssd2, wb_clk_i, wb_rst_i, wbs_stb_i, wbs_cyc_i, wbs_we_i, wbs_sel_i, wbs_dat_i, wbs_adr_i, wbs_ack_o, wbs_dat_o, la_data_in, la_data_out, la_oenb
, io_in, io_out, io_oeb, analog_io, user_clock2, user_irq);
  inout [28:0] analog_io;
  input [37:0] io_in;
  output [37:0] io_oeb;
  output [37:0] io_out;
  input [127:0] la_data_in;
  output [127:0] la_data_out;
  input [127:0] la_oenb;
  input user_clock2;
  output [2:0] user_irq;
  inout vccd1;
  inout vccd2;
  inout vdda1;
  inout vdda2;
  inout vssa1;
  inout vssa2;
  inout vssd1;
  inout vssd2;
  input wb_clk_i;
  input wb_rst_i;
  output wbs_ack_o;
  input [31:0] wbs_adr_i;
  input wbs_cyc_i;
  input [31:0] wbs_dat_i;
  output [31:0] wbs_dat_o;
  input [3:0] wbs_sel_i;
  input wbs_stb_i;
  input wbs_we_i;
  sky130_sram_1kbyte_1rw1r_32x256_8 openram_1kB (
    .addr0(wbs_adr_i[7:0]),
    .addr1(wbs_adr_i[15:8]),
    .clk0(user_clock2),
    .clk1(user_clock2),
    .csb0(la_data_in[0]),
    .csb1(la_data_in[1]),
    .din0(wbs_dat_i),
    .dout0(la_data_out[31:0]),
    .dout1(la_data_out[63:32]),
    .vccd1(vccd1),
    .vssd1(vssd1),
    .web0(wbs_we_i),
    .wmask0(wbs_sel_i)
  );
endmodule
